[package]
name = "oro-torus"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-common = { path = "../oro-common" }
oro-package-spec = { path = "../oro-package-spec" }
oro-manifest = { path = "../oro-manifest" }

async-trait = "0.1.52"
async-tar = "0.2.0"
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
cacache = "9.0.0"
bincode = "1.3.1"
ssri = "7.0.0"
http-types = "2.3.0"
mkdirp = "1.0.0"
dashmap = "4.0.0-rc6"
url = "2.2.0"
tempfile = "3.1.0"
async-process = "1.0.1"
which = "4.0.2"

serde = "1.0.126"
