[package]
name = "cmd-shell"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-command = { path = "../../../crates/oro-command" }
oro-config = { path = "../../../crates/oro-config" }
oro-diagnostics = { path = "../../../crates/oro-diagnostics" }
clap = { git = "https://github.com/zkat/clap" }

async-trait = "0.1.19"
directories = "2.0.2"
log = "0.4.11"
ssri = "6.0.0"
