[package]
name = "oro-gui-handler"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
oro-config = { path = "../oro-config" }

anyhow = "1.0.24"
async-trait = "0.1.19"
erased-serde = "0.3.12"
typetag = "0.1.5"
