[package]
name = "oro-handle-ping"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-gui-handler = { path = "../../../crates/oro-gui-handler" }
oro-client = { path = "../../../crates/oro-client" }
oro-config = { path = "../../../crates/oro-config" }

anyhow = "1.0.24"
erased-serde = "0.3.12"
tauri = { version = "0.9", features = [ "event" ] }
async-trait = "0.1.19"
typetag = "0.1.5"
serde = "1.0.115"
serde_json = "1.0.57"
