[package]
name = "oro-cmd-ping"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"

[dependencies]
oro-torus = { path = "../../crates/oro-torus" }
oro-command = { path = "../../crates/oro-command" }
oro-common = { path = "../../crates/oro-common" }
